config/routes.rb
GroupizeDesignerApp::Application.routes.draw do

  resources :snacks

  root to: 'snacks#index'
end

app/models/snack.rb
class Snack < ActiveRecord::Base
  attr_accessible :calories, :description, :last_restock_date, :name, :restock_frequency_days

  def remaining_days
    if restock_frequency_days
      rand(restock_frequency_days)
    else
      "N/A"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController

  def new
    @snack = Snack.new
  end

  def create
    @snack = Snack.new(params[:snack])

    @snack.last_restock_date = 1.day.ago
    if @snack.save!
      flash[:notice] = "Thanks for suggesting!"
      redirect_to snacks_path
    else
      flash[:error] = "Problems. We can't get that snack"
      render :new
    end
  end

  def index
    @snacks = Snack.all
    @snack = Snack.new
  end

  def edit
    @snack = Snack.find(params[:id])
  end

  def update
    @snack = Snack.find(params[:id])
    if @snack.save!
      flash[:notice] = "Thanks for suggesting!"
      redirect_to snacks_path
    else
      flash[:error] = "Problems. We can't get that snack"
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<%= content_tag :header, class: "header" do %>
  <%= content_tag :div do %>
    <%= link_to root_path do %>
      <h1 class="logo" data-role="logo">Snack Logo</h1>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="fullWidthRow footer">
	<div class="row footerContent">
		<div class="small-4 columns">
			<a href="https://github.com/cmpowell/groupize_design_problem" target="_blank" alt="Source Code for Groupize's design problem">Source Code</a>
		</div>
		<div class="small-4 columns">
			<a href="humans.txt" target="_blank" alt="Who built the Groupize design problem and how">Credits</a>
		</div>
		<div class="small-4 columns">
			<a href="http://www.groupize.com" target="_blank" alt="Groupize, Group Travel Made Easy"><img src="/assets/groupize-logo.png"></a>
		</div>
	</div>
</div>

app/views/layouts/_modals.html.erb
<!-- Request Snack Modal -->
    <div id="requestSnackModal" class="reveal-modal medium">
      <h1>Request a New Snack</h1>
      <p>We can't promise we'll get it, but suggest a snack and we'll do our best!</p>
      <p>Sincerely,</p>
      <p>Your Admin Team</p>
      <%= render partial: 'form', locals: { include_date: false } %>
      <a class="close-reveal-modal">&#215;</a>
    </div>
    <!-- Edit Snack Modal -->
    <div id="editSnackModal" class="reveal-modal medium">
    <h1>Change the Snack</h1>
    <p>Update the last purchase date or change info about the snack</p>
    <%= render partial: 'form', locals: { include_date: true } %>
    <a class="close-reveal-modal">&#215;</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Groupize Office Snack Tracker Extraordinaire" %></title>

    <link rel="author" href="humans.txt" />

  	<%= stylesheet_link_tag    "application" %>
    <link href='http://fonts.googleapis.com/css?family=Molengo' rel='stylesheet' type='text/css'>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    <%= render "layouts/footer" %>
    
    <%= javascript_include_tag "application" %>

    <%= render "layouts/modals" %>
  </div>
  </body>
</html>

app/views/snacks/_editForm.html.erb
<%= simple_form_for @snack do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :calories %>
  <% if include_date %>
    <%= f.input :last_restock_date, label: 'Date You Last Purchased This Snack' %>
  <% end %>
  <%= f.input :restock_frequency_days, label: 'Restock Frequency (days)' %>
  <%= f.button :submit %>
<% end %>

app/views/snacks/_form.html.erb
<%= simple_form_for(@snack, html: { class: 'snackForm' }) do |f| %>

  <div class="row">

  	<div class="small-12 large-6 columns">
  		<%= f.input :name, label: " Snack Name" %>
  	</div>
  </div>

  <div class="row">
  	<div class="small-12 columns">
  		<%= f.input :description %>
  	</div>
  </div>
  <div class="row">
  	<div class="small-12 large-6 columns">
  		<%= f.input :calories %>
  	</div>
  	<div class="small-12 large-6 columns">
  		<%= f.input :restock_frequency_days, label: 'Restock Frequency (days)' %>
  	</div>
  </div>

  <% if include_date %>
    <div class="row">
    	<div class="small-12 large-4 columns selectStyles">
    		<%= f.input :last_restock_date, label: 'Date You Last Purchased This Snack' %>
    	</div>
    </div>
  <% end %>
  
  <div class="row">
  	<div class="small-12 large-6 columns">
  		<%= f.button :submit, :class => "button large expand" %>
  	</div>
  </div>

<% end %>

app/views/snacks/edit.html.erb
<h1>Change the Snack</h1>
<p>Update the last purchase date or change info about the snack</p>
<%= render partial: 'editForm', locals: { include_date: true } %>

app/views/snacks/index.html.erb
<div class="row card">
  <div class="small-12 columns">
    <h1>Kitchen Snack Central</h1>
  </div>
  <div class="small-12 large-6 columns">
    <p>These are the snacks we keep in the company kitchen. Enjoy!</p>
    
  </div>
  <div class="small-12 large-6 columns">
    <p>Don't see anything you like?</p>
    <%= link_to "Request a New Snack", new_snack_path, :class => "button", :"data-reveal-id" => "requestSnackModal" %>
  </div>
  <hr>
  <div class="show-for-small small-12 columns panel">
    <p>Swipe right to see all of the table!</p>
  </div>
  
  <table class="responsive snackTable">
    <thead class="snackTable">
      <tr>
        <th class="snackTable">Snack Name</th>
        <th class="snackTable"><span data-tooltip data-options="disable-for-touch:true" class="has-tip" title="Time until refill needed, measured in days">TTR</span></th>
        <th class="snackTable"><span data-tooltip data-options="disable-for-touch:true" class="has-tip" title="Calories per serving of the snack">Calories</span></th>
        <th class="snackTable">Description</th>
      </tr>
    </thead>
    <tbody class="snackTable">
      <% @snacks.each do |snack| %>
        <tr>
          <td class="snackTable"><%= link_to snack.name, edit_snack_path(snack), :"data-reveal-id" => "editSnackModal"%></td>
          <td class="snackTable"><%= snack.remaining_days %> (of <%= snack.restock_frequency_days %>)</td>
          <td class="snackTable"><%= snack.calories %></td>
          <td class="snackTable"><%= snack.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  </div>
</div>

app/views/snacks/new.html.erb
<h1>Request a New Snack</h1>
<p>We can't promise we'll get it, but suggest a snack and we'll do our best!</p>
<p>Sincerely,</p>
<p>Your Admin Team</p>
<%= render partial: 'form', locals: { include_date: false } %>

app/views/snacks/show.html.erb
<h1>SnacksController#show</h1>
<p>Find me in app/views/snacks_controller/show.html.erb</p>